pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "my-angular21-app"
        DOCKER_TAG = "latest"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/dhrunam/mcs_frontend_new.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                script {
                    sh """
                    if [ \$(docker ps -aq -f name=my-angular-container) ]; then
                        docker rm -f my-angular-container || true
                    fi
                    """
                }
            }
        }

        stage('Run New Container') {
            steps {
                script {
                    sh """
                    docker run -d --name my-angular-container \
                        -p 8080:80 \
                        ${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Angular 21 deployed successfully!"
        }
        failure {
            echo "Deployment failed!"
        }
    }
}
